P = vim.pretty_print

require("hb/autocmds")
require("hb/plugins")
require("hb/keymaps")
require("hb/colorscheme")
require("hb/misc")
require("hb/git")
require("hb/nvim-tree")
require("hb/statusline")
require("hb/telescope")
require("hb/treesitter")
require("hb/lsp")
require("hb/compe")
require("hb/dap")
require("hb/neotest")
