P = function(...)
    print(vim.inspect(...))
end

require("hb/options")
require("hb/plugins")
require("hb/keymaps")
require("hb/colorscheme")
require("hb/misc")
require("hb/git")
require("hb/nvim-tree")
require("hb/statusline")
require("hb/telescope")
require("hb/treesitter")
require("hb/lsp")
require("hb/compe")
require("hb/dap")
require("hb/ultest")
