return {
    {
        "nvim-treesitter/nvim-treesitter",
        -- LazyVim 对 ensure_installed 声明了 opts_extend，直接给列表即可与默认值合并
        opts = {
            ensure_installed = {
                "bash",
                "c",
                "cpp",
                "go",
                "gomod",
                "gowork",
                "gosum",
                "gotmpl",
                "comment",
                "sql",
                "java",
                "javascript",
                "json",
                "lua",
                "markdown",
                "markdown_inline",
                "mermaid",
                "python",
                "regex",
                "rust",
                "typescript",
                "vim",
                "vimdoc",
                "git_config",
                "gitignore",
                "gitattributes",
                "gitcommit",
                "git_rebase",
            },
        },
    },
}
