vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.o.clipboard = "unnamedplus"
vim.o.number = true
vim.o.relativenumber = true
vim.o.timeout = true
vim.o.ttimeout = true
vim.o.timeoutlen = 500 -- Time out on mappings
vim.o.updatetime = 100 -- Idle time to write swap and trigger CursorHold
vim.o.ttimeoutlen = 10 -- Time out on key codes
vim.o.exrc = true
vim.o.hidden = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.wrap = false
vim.o.ignorecase = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.writebackup = false
vim.o.undodir = os.getenv("HOME") .. "/.config/nvim_undir"
vim.o.undofile = true
vim.o.incsearch = true
vim.o.termguicolors = true
vim.o.scrolloff = 8
vim.o.showmode = false
vim.o.signcolumn = "yes"
vim.o.completeopt = "menu,menuone,noselect"
vim.o.mouse = ""
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.cmdheight = 1
vim.o.shortmess = vim.o.shortmess .. "c"
